### ISSUE TITLE
Update to allow `fuge build` support

### ISSUE THREAD

**Issue by mcdonnelldean** [nearform/vidi-concorda-nodezoo-system#4]
Dockerfile's for each service need to be in order for this to work.

**Comment by mcdonnelldean** [comment]
@ckiss @salmanm should be able to show you how they did this, you basically add a build property in the fuge-config that runs npm run build. Then you can do fuge build system.yml and it will do a full build.

**Comment by salmanm** [comment]
Sure @ckiss, lets connect on Slack if you need to discuss this.

**Comment by ckiss** [comment]
done by #8
